/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTermin;

import controller.ClientController;
import domain.Doktor;
import domain.Pacijent;
import domain.StavkaTermina;
import domain.Termin;
import domain.Usluga;
import forms.MainForm;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import models.TableModelStavkeTermina;

/**
 *
 * @author PC
 */
public class FormDetaljiTermina extends javax.swing.JDialog {

    private Termin t;

    public FormDetaljiTermina(JDialog parent, boolean modal, Termin t) {
        super(parent, modal);
        initComponents();
        this.t = t;
        setLocationRelativeTo(null);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnObrisiUslugu = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeTermina = new javax.swing.JTable();
        cmbUsluga = new javax.swing.JComboBox();
        txtCenaUsluge = new javax.swing.JFormattedTextField();
        cmbPacijent = new javax.swing.JComboBox();
        cmbDoktor = new javax.swing.JComboBox();
        txtDatumVreme = new javax.swing.JFormattedTextField();
        txtCenaTermina = new javax.swing.JFormattedTextField();
        lblObjasnjenje = new javax.swing.JLabel();
        btnOdustani = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        lblObavestenje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalji termina"));

        jLabel1.setText("Pacijent:");

        jLabel2.setText("Doktor:");

        jLabel3.setText("Datum i vreme:");

        jLabel4.setText("Cena termina:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usluge termina"));

        jLabel5.setText("Usluga:");

        jLabel6.setText("Posebna cena:");

        btnObrisiUslugu.setText("Obrisi uslugu");
        btnObrisiUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUsluguActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj uslugu");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        tblStavkeTermina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeTermina);

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsluga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUslugaItemStateChanged(evt);
            }
        });

        txtCenaUsluge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnObrisiUslugu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCenaUsluge))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCenaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiUslugu)
                    .addComponent(btnDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        cmbPacijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDoktor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDatumVreme.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm"))));

        txtCenaTermina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lblObjasnjenje.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N

        btnOdustani.setBackground(new java.awt.Color(255, 102, 102));
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(255, 102, 102));
        btnObrisi.setText("Otkazi termin");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(102, 102, 255));
        btnIzmeni.setText("Sacuvaj izmene");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        lblObavestenje.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        lblObavestenje.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblObjasnjenje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(cmbPacijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59)
                                .addComponent(cmbDoktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatumVreme)
                                    .addComponent(txtCenaTermina)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblObavestenje)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblObavestenje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblObjasnjenje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCenaTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {
            Doktor doktor = (Doktor) cmbDoktor.getSelectedItem();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            Date datumVreme = sdf.parse(txtDatumVreme.getText());
            
            if (datumVreme.before(new Date()) 
                    || datumVreme.equals(new Date())) {
              
                 JOptionPane.showMessageDialog(this, "Termin mora biti rezervisan nakon danasnjeg datuma!", "Upozorenje",JOptionPane.WARNING_MESSAGE);
                return;
            }

            Calendar cal = Calendar.getInstance();
            cal.setTime(datumVreme);

            if (cal.get(Calendar.MINUTE) != 0) {
              
                  JOptionPane.showMessageDialog(this, "Termin moze biti zakazan samo na ceo sat!", "Upozorenje",JOptionPane.WARNING_MESSAGE);

                return;
            }

            double cenaTermina = Double.parseDouble(txtCenaTermina.getText());

            TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavkeTermina.getModel();

            t.setDoktor(doktor);
            t.setDatumVreme(datumVreme);
            t.setCenaTermina(cenaTermina);
            t.setStavkeTermina(tm.getLista());

            ClientController.getInstance().updateTermin(t);
            FormPretragaTermina fp = (FormPretragaTermina) getParent();
            fp.refreshTable();
            
              JOptionPane.showMessageDialog(this, "Uspesno ste izmenili termin.", "Obavestenje",JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiTermina.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "otkazete ovaj termin?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().deleteTermin(t);
                FormPretragaTermina fp = (FormPretragaTermina) getParent();
                fp.refreshTable();
                
                  JOptionPane.showMessageDialog(this, "Uspesno ste otkazali termin.", "Obavestenje",JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FormDetaljiTermina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnObrisiUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUsluguActionPerformed

        int row = tblStavkeTermina.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavkeTermina.getModel();

            StavkaTermina st = tm.getSelectedStavka(row);

            double cenaTermina = Double.parseDouble(txtCenaTermina.getText());
            txtCenaTermina.setText(String.valueOf(cenaTermina - st.getCenaStavke()));

            tm.obrisiStavku(row);
        }
    }//GEN-LAST:event_btnObrisiUsluguActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        Usluga u = (Usluga) cmbUsluga.getSelectedItem();

        TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavkeTermina.getModel();
        if (tm.postojiUsluga(u)) {
          
              JOptionPane.showMessageDialog(this, "Vec ste uneli tu uslugu za ovaj termin!", "Greska",JOptionPane.ERROR_MESSAGE);

            return;
        }

        double cena;

        if (txtCenaUsluge.getText().isEmpty()) {
            cena = u.getCena();
        } else {
            cena = Double.parseDouble(txtCenaUsluge.getText());
        }

        if (cena < 500 || cena > 1000000) {
            //JOptionPane.showMessageDialog(this, "Cena usluge mora biti izmedju 500 i 1000000!");
              JOptionPane.showMessageDialog(this, "Cena usluge mora biti izmedju 500 i 1000000!", "Upozorenje",JOptionPane.WARNING_MESSAGE);

            return;
        }

        StavkaTermina st = new StavkaTermina(t, -1, cena, u);

        tm.dodajStavku(st);

        double cenaTermina = Double.parseDouble(txtCenaTermina.getText());
        txtCenaTermina.setText(String.valueOf(cenaTermina + st.getCenaStavke()));

    }//GEN-LAST:event_btnDodajActionPerformed

    private void cmbUslugaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUslugaItemStateChanged

        if (cmbUsluga.getSelectedItem() != null) {
            txtCenaUsluge.setText("");
        }

    }//GEN-LAST:event_cmbUslugaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiUslugu;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JComboBox cmbDoktor;
    private javax.swing.JComboBox cmbPacijent;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblObavestenje;
    private javax.swing.JLabel lblObjasnjenje;
    private javax.swing.JTable tblStavkeTermina;
    private javax.swing.JFormattedTextField txtCenaTermina;
    private javax.swing.JFormattedTextField txtCenaUsluge;
    private javax.swing.JFormattedTextField txtDatumVreme;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        setTitle("Detalji termina");
        cmbPacijent.getModel().setSelectedItem(t.getPacijent());
        cmbPacijent.setEnabled(false);
        cmbDoktor.getModel().setSelectedItem(t.getDoktor());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        txtDatumVreme.setText(sdf.format(t.getDatumVreme()));
        txtCenaTermina.setText(String.valueOf(t.getCenaTermina()));
        txtCenaTermina.setEnabled(false);
        popuniDoktore();
        popuniUsluge();
        tblStavkeTermina.setModel(new TableModelStavkeTermina(t));
        lblObjasnjenje.setText("Termin moze biti zakazan samo na ceo sat!");

        if (t.getDatumVreme().before(new Date())
                || t.getDatumVreme().equals(new Date())) {
            lblObavestenje.setText("Ovaj termin je prosao, ne mozete ga menjati niti otkazivati!");
            btnObrisi.setEnabled(false);
            btnIzmeni.setEnabled(false);
        }

    }

    private void popuniDoktore() {
        try {
            ArrayList<Doktor> doktori = ClientController.getInstance().getAllDoktor();

            cmbDoktor.removeAllItems();

            for (Doktor doktor : doktori) {
                cmbDoktor.addItem(doktor);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniUsluge() {
        try {
            ArrayList<Usluga> usluge = ClientController.getInstance().getAllUsluga();

            cmbUsluga.removeAllItems();

            for (Usluga usluga : usluge) {
                cmbUsluga.addItem(usluga);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
